"$schema" = 'https://starship.rs/config-schema.json'

format = """
$env_var\
$directory\
$git_branch\
$git_status\
$python\
$rust\
$nodejs\
$docker_context\
$kubernetes\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[env_var.NODEID]
format = "[$env_value]($style) "
style = "bold yellow"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[cmd_duration]
min_time = 2_000
format = "[$duration]($style) "

[python]
python_binary = "python3.12"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
format = "[$symbol($version )]($style)"

[nodejs]
format = "[$symbol($version )]($style)"
detect_files = ["package.json"]
detect_folders = ["node_modules"]

[docker_context]
format = "[$symbol$context]($style) "
only_with_files = true

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
detect_files = ["k8s", "kubernetes", "Dockerfile"]
